name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm install --package-lock-only
          npm ci
          
      - name: Build Frontend
        working-directory: ./frontend
        env:
          CI: false
          PUBLIC_URL: /SensorAnomalyDetectionSuite
        run: npm run build
        
      - name: Debug Build Output
        working-directory: ./frontend
        run: ls -la build
        
      - name: Add .nojekyll file
        working-directory: ./frontend
        run: touch build/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          force_orphan: true
